name: Compile LaTeX
on: [ push ]
jobs:
  container:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build using latexmk
        run: latexmk -pdf -output-directory=out -xelatex resume.tex

      - name: Upload document
        uses: actions/upload-artifact@v4
        with:
          name: main-document
          path: out/resume.pdf

      - name: Push artifact to branch
        uses: actions/checkout@v4
        ref: artifact
        run: |
          git config --global user.name 'Artifact Pusher'
          git config --global user.email 'gurrit@users.noreply.github.com'
          git commit -m "update resume artifact"
          git push
