name: Compile LaTeX
on: 
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-latex:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build using latexmk
        run: latexmk -pdf -output-directory=out -xelatex resume.tex

      - name: Upload document
        uses: actions/upload-artifact@v4
        with:
          name: main-document
          path: out/resume.pdf

  push-branch:
    runs-on: ubuntu-latest
    needs: build-latex
    steps: 
      - name: Checkout branch
        uses: actions/checkout@v4
      
      - name: download artifact
        uses: actions/download-artifact@v4
        with: 
          name: main-document

      - name: Push updated CV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan cv-pdf
          git rm --cache -r . 
          git add resume.pdf -f
          git commit -m "Update CV PDF"
          git push --set-upstream origin cv-pdf --force
